package igu;

import javax.swing.JOptionPane;

public class cargaDatos extends javax.swing.JFrame {

    /** Creates new form cargaDatos */
    public cargaDatos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblcategoria = new javax.swing.JLabel();
        lblproveed = new javax.swing.JLabel();
        txtmodifCateg = new javax.swing.JTextField();
        txtmodifProveed = new javax.swing.JTextField();
        cbocategoria = new javax.swing.JComboBox<>();
        cboproveed = new javax.swing.JComboBox<>();
        btnagregarC = new javax.swing.JButton();
        btnagregarP = new javax.swing.JButton();
        btneditarP = new javax.swing.JButton();
        btneditarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\EuroCortinas\\assets\\icon\\logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        lblcategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblcategoria.setText("CATEGORIA");

        lblproveed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblproveed.setText("PROVEEDOR");

        txtmodifCateg.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtmodifProveed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        btnagregarC.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarC.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\EuroCortinas\\assets\\icon\\pngwing.com.png")); // NOI18N
        btnagregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarCActionPerformed(evt);
            }
        });

        btnagregarP.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarP.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\EuroCortinas\\assets\\icon\\pngwing.com.png")); // NOI18N
        btnagregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarPActionPerformed(evt);
            }
        });

        btneditarP.setForeground(new java.awt.Color(255, 255, 255));
        btneditarP.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\EuroCortinas\\assets\\icon\\editar.png")); // NOI18N
        btneditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarPActionPerformed(evt);
            }
        });

        btneditarC.setForeground(new java.awt.Color(255, 255, 255));
        btneditarC.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\EuroCortinas\\assets\\icon\\editar.png")); // NOI18N
        btneditarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcategoria)
                        .addGap(18, 18, 18)
                        .addComponent(cbocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneditarC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblproveed)
                                .addGap(18, 18, 18)
                                .addComponent(cboproveed, 0, 196, Short.MAX_VALUE))
                            .addComponent(txtmodifProveed)
                            .addComponent(txtmodifCateg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnagregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnagregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(203, 203, 203))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblcategoria)
                    .addComponent(cbocategoria)
                    .addComponent(btneditarC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmodifCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarC))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblproveed)
                        .addComponent(cboproveed)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmodifProveed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarP))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarPActionPerformed
        if (txtmodifProveed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay proveedor que agregar");
        }else {
            cboproveed.addItem(txtmodifProveed.getText());
            txtmodifProveed.setText("");
        }
    }//GEN-LAST:event_btnagregarPActionPerformed

    private void btneditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarPActionPerformed
        String seleccion = (String) cboproveed.getSelectedItem();
        txtmodifProveed.setText((String) cboproveed.getSelectedItem());
        cboproveed.removeItem(seleccion);
    }//GEN-LAST:event_btneditarPActionPerformed

    private void btnagregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarCActionPerformed
        if (txtmodifCateg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay categoria que agregar");
        }else {
            cbocategoria.addItem(txtmodifCateg.getText());
            
            txtmodifCateg.setText("");
        }
    }//GEN-LAST:event_btnagregarCActionPerformed

    private void btneditarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarCActionPerformed
        String seleccion = (String) cbocategoria.getSelectedItem();
        txtmodifCateg.setText((String) cbocategoria.getSelectedItem());
        cbocategoria.removeItem(seleccion);
    }//GEN-LAST:event_btneditarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarC;
    private javax.swing.JButton btnagregarP;
    private javax.swing.JButton btneditarC;
    private javax.swing.JButton btneditarP;
    private javax.swing.JComboBox<String> cbocategoria;
    private javax.swing.JComboBox<String> cboproveed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblproveed;
    private javax.swing.JTextField txtmodifCateg;
    private javax.swing.JTextField txtmodifProveed;
    // End of variables declaration//GEN-END:variables

}
