package igu;

import javax.swing.JOptionPane;
import logica.Insumo;
import persistencia.ControladoraPersistencia;

public class cargaInsumos extends javax.swing.JFrame {

    public cargaInsumos() {
        initComponents();
        setBounds(0, 0, 629, 558);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        lblinsumo = new javax.swing.JLabel();
        lblcategoria = new javax.swing.JLabel();
        lblproveed = new javax.swing.JLabel();
        lblespecif = new javax.swing.JLabel();
        lblumed = new javax.swing.JLabel();
        lblstockI = new javax.swing.JLabel();
        lblstockA = new javax.swing.JLabel();
        lblstockMIN = new javax.swing.JLabel();
        lblcosto = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtinsumo = new javax.swing.JTextField();
        txtespecif = new javax.swing.JTextField();
        txtumed = new javax.swing.JTextField();
        txtstockI = new javax.swing.JTextField();
        txtstockA = new javax.swing.JTextField();
        txtstockMIN = new javax.swing.JTextField();
        txtcosto = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        cbocategoria = new javax.swing.JComboBox<>();
        cboproveed = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\EuroCortinas\\assets\\icon\\logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblcodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblcodigo.setText("CODIGO");

        lblinsumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblinsumo.setText("INSUMO");

        lblcategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblcategoria.setText("CATEGORIA");

        lblproveed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblproveed.setText("PROVEEDOR");

        lblespecif.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblespecif.setText("ESPECIFICACIONES");

        lblumed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblumed.setText("UNIDAD MEDIDA");

        lblstockI.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblstockI.setText("STOCK INICIAL");

        lblstockA.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblstockA.setText("STOCK ACTUAL");

        lblstockMIN.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblstockMIN.setText("STOCK MIN");

        lblcosto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblcosto.setText("COSTO");

        lblprecio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblprecio.setText("PRECIO");

        txtcodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtinsumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtespecif.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtumed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtstockI.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtstockA.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtstockMIN.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtcosto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtprecio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        btnguardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        cbocategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black Out" }));

        cboproveed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Printemps" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodigo)
                            .addComponent(lblinsumo)
                            .addComponent(lblcategoria)
                            .addComponent(lblproveed))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtinsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(cbocategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cboproveed, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblespecif)
                            .addComponent(lblumed)
                            .addComponent(lblstockI)
                            .addComponent(lblstockA)
                            .addComponent(lblstockMIN)
                            .addComponent(lblcosto)
                            .addComponent(lblprecio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstockMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstockA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstockI, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtumed, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtespecif, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlimpiar)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsumo)
                    .addComponent(txtinsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcategoria)
                    .addComponent(cbocategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblproveed)
                    .addComponent(cboproveed, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblespecif)
                    .addComponent(txtespecif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblumed)
                    .addComponent(txtumed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstockI)
                    .addComponent(txtstockI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstockA)
                    .addComponent(txtstockA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstockMIN)
                    .addComponent(txtstockMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcosto)
                    .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar)
                    .addComponent(btnlimpiar))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        String[] datosInsumo = new String[11];
        boolean flag = true;

        datosInsumo[0] = txtcodigo.getText();
        datosInsumo[1] = txtinsumo.getText();
        datosInsumo[2] = (String) cbocategoria.getSelectedItem();
        datosInsumo[3] = (String) cboproveed.getSelectedItem();
        datosInsumo[4] = txtespecif.getText();
        datosInsumo[5] = txtumed.getText();
        datosInsumo[6] = (validarNumero(txtstockI.getText())) ? txtstockI.getText() : "no";
        datosInsumo[7] = (validarNumero(txtstockA.getText())) ? txtstockA.getText() : "no";
        datosInsumo[8] = (validarNumero(txtstockMIN.getText())) ? txtstockMIN.getText() : "no";
        datosInsumo[9] = (validarNumero(txtcosto.getText())) ? txtcosto.getText() : "no";
        datosInsumo[10] = (validarNumero(txtprecio.getText())) ? txtprecio.getText() : "no";

        for (String dato : datosInsumo) {
            if (dato.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Deben completarse todos los campos");
                flag = false;
                break;
            } else if (dato == "no") {
                JOptionPane.showMessageDialog(this, "No coinciden los tipos");
                flag = false;
                break;
            }
        }
        if (flag) {
            Insumo insumo = new Insumo(datosInsumo[0], datosInsumo[1], datosInsumo[2],
                    datosInsumo[3], datosInsumo[4], datosInsumo[5], Float.parseFloat(datosInsumo[6]),
                    Float.parseFloat(datosInsumo[7]), Integer.parseInt(datosInsumo[8]),
                    Float.parseFloat(datosInsumo[9]), Float.parseFloat(datosInsumo[10]));
            ControladoraPersistencia control = new ControladoraPersistencia();
//            control.crearInsumo(insumo);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void limpiar() {
        txtcodigo.setText("");
        txtinsumo.setText("");
        cbocategoria.setSelectedIndex(0);
        cboproveed.setSelectedIndex(0);
        txtespecif.setText("");
        txtumed.setText("");
        txtstockI.setText("");
        txtstockA.setText("");
        txtstockMIN.setText("");
        txtcosto.setText("");
        txtprecio.setText("");
    }

    private boolean validarNumero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox<String> cbocategoria;
    private javax.swing.JComboBox<String> cboproveed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcosto;
    private javax.swing.JLabel lblespecif;
    private javax.swing.JLabel lblinsumo;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblproveed;
    private javax.swing.JLabel lblstockA;
    private javax.swing.JLabel lblstockI;
    private javax.swing.JLabel lblstockMIN;
    private javax.swing.JLabel lblumed;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtespecif;
    private javax.swing.JTextField txtinsumo;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstockA;
    private javax.swing.JTextField txtstockI;
    private javax.swing.JTextField txtstockMIN;
    private javax.swing.JTextField txtumed;
    // End of variables declaration//GEN-END:variables
}
